"""Baseline migration

Revision ID: 29ecdfbd1229
Revises: 
Create Date: 2026-04-05 15:27:02.782226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ecdfbd1229'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_saved_content_has_extraction'), table_name='saved_content', postgresql_where='(extracted_text IS NOT NULL)')
    op.create_index(op.f('ix_users_provider_name'), 'users', ['provider_name'], unique=False)
    op.create_index(op.f('ix_users_provider_user_id'), 'users', ['provider_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_provider_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_provider_name'), table_name='users')
    op.create_index(op.f('idx_saved_content_has_extraction'), 'saved_content', ['user_id'], unique=False, postgresql_where='(extracted_text IS NOT NULL)')
    # ### end Alembic commands ###
